---
title: "Wine"
author: "Andy"
date: "September 21, 2015"
output: 
  pdf_document: 
    fig_crop: no
    keep_tex: yes
    latex_engine: xelatex
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width=100)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, messages=FALSE, cache=T)
```

```{r}
library("lattice")
library("nortest")
library("moments")
library("corrplot")
```

```{r}
full.summary <- function(w.sample) {
  c(diff(range(w.sample)), 
    min(w.sample), 
    max(w.sample), 
    mean(w.sample), 
    quantile(w.sample, c(0.5, 0.25, 0.75), names = F), 
    
    var(w.sample), 
    var(w.sample) * (length(w.sample) - 1) / length(w.sample), 
    sd(w.sample), 
    
    sd(w.sample) * sqrt((length(w.sample) - 1) / length(w.sample)) / mean(w.sample),
    skewness(w.sample), 
    kurtosis(w.sample), 
    kurtosis(w.sample) - 3)
}
```

```{r}
wine <- list(
      red.wine = read.csv("winequality-red.csv", sep = ";", header = T),
      white.wine = read.csv("winequality-white.csv", sep = ";", header = T)
)

head(wine$red.wine)
head(wine$white.wine)
```

Все признаки количественные. Посмотрим какие непрерывные, а какие дискретные.

```{r}
sapply(wine$red.wine, function(x) length(unique(x)) / dim(wine$red.wine)[1])
sapply(wine$white.wine, function(x) length(unique(x)) / dim(wine$white.wine)[1])

sapply(wine$red.wine, function(x) sum(x == max(x)))
sapply(wine$white.wine, function(x) sum(x == max(x)))
```

Все кроме density дискретные.

```{r}
lapply(wine$red.wine, function(x) histogram( ~ x))
lapply(wine$white.wine, function(x) histogram( ~ x))
```

```{r, fig.width = 15, fig.height = 15}
splom(~ wine$red.wine)
splom(~ wine$white.wine)
```


```{r, fig.width = 15, fig.height = 15}
by(wine$red.wine, wine$red.wine$quality, function(x) splom(~ x - x$quality, main = paste("Quality: ", x$quality[1])))
by(wine$white.wine, wine$white.wine$quality, function(x) splom(~ x - x$quality, main = paste("Quality: ", x$quality[1])))
```

```{r}
p1 <- splom(~ wine$red.wine) 
p2 <- splom(~ subset(wine$red.wine, wine$red.wine$quality == 5))
plot(p1, split = c(1, 1, 2, 1))
plot(p2, split = c(2, 1, 2, 1), newpage = FALSE)
```

```{r}
lapply(wine$red.wine, shapiro.test)
lapply(wine$red.wine, function(x) { shapiro.test(log(x)) } )

lapply(wine$white.wine, shapiro.test)
lapply(wine$white.wine, function(x) { shapiro.test(log(x)) } )
```


```{r}
lapply(wine$red.wine, summary)
lapply(wine$red.wine, function(x) bwplot(~ x | wine$red.wine$quality))
```

Убираем два аутлайера.
```{r}
bwplot(~total.sulfur.dioxide, data = wine$red.wine)
subset(wine$red.wine, wine$red.wine$total.sulfur.dioxide > 170)

wine$red.wine <- wine$red.wine[-which(wine$red.wine$total.sulfur.dioxide > 170), ]
```

Еще аутлайеры
```{r}
bwplot(~sulphates, data = wine$red.wine)
subset(wine$red.wine, wine$red.wine$sulphates > 1.7)

wine$red.wine <- wine$red.wine[-which(wine$red.wine$sulphates > 1.7),]
```

```{r}
bwplot(~chlorides, data = wine$red.wine)
subset(wine$red.wine, wine$red.wine$chlorides > 0.6)

wine$red.wine <- wine$red.wine[-which(wine$red.wine$chlorides > 0.6),]
```


# Корреляции

```{r}
corr <- cor(wine$red.wine, method = "pearson")
corrplot(corr, method="number")

corr <- cor(wine$red.wine, method = "spearman")
corrplot(corr, method="number")
```

# Линейная регрессия

```{r}
lin.fit <- lm(quality ~ volatile.acidity + chlorides + free.sulfur.dioxide + total.sulfur.dioxide + pH + sulphates + alcohol, data = wine$red.wine)
summary(lin.fit)
confint(lin.fit)
library(aod)
wald.test(b = coef(lin.fit), Sigma = vcov(lin.fit), Terms = 1:4)
```


??? 
```{r}
library(MASS)
st.res <- studres(lin.fit)
head(st.res)
plot(y = st.res, x = lin.fit$fitted.values)
```

