---
title: "NonlinearRegression"
date: "September 24, 2015"
output: html_document
---

Промоделируем данные так, чтобы они заведомо были нелинейными. Для этого будем использовать сигмоид.
Первый столбец будет равномерно распределен на $[1, 1000]$, второй будет фактором, а третий --- сигмоид от первых двух (с заданными параметрами).

```{r}
weights = c(0.02,0.5,1.5,3.2)
sigmoid <- function(x,y, alpha = 0.1) { 0.75 / (1 + exp(-(x * alpha + weights[y]))) }

N = 100
df = data.frame(x=runif(N,1,1000), y = as.factor(sample(c(1,2,3,4),size=100, prob=c(0.5,0.25,0.1,0.15), replace = TRUE)))
head(df)
```

```{r}
rmse <- function(obs, theor) {
  sqrt(sum((obs - theor)^2)/length(obs))
}
```

```{r}
go <- function(perc = 0.8) {
  df <- data.frame(x=runif(N,1,1000), y = as.factor(sample(c(1,2,3,4),size=100, prob=c(0.5,0.15,0.2,0.15), replace = TRUE)))
  df$z = apply(df, function(row) { sigmoid(as.numeric(row[1]), as.numeric(row[2])) + rnorm(n=1, sd=2)}, MARGIN=1)
  train.ind <- sample(1:nrow(df), nrow(df) * perc)
  train <- df[train.ind,]
  test <- df[-train.ind,]
  lin.fit <- lm(z ~ ., data = train)
  predicted.lin <- predict(lin.fit, test)
  start = sapply(train.ind, function(i) { 1.0 / (1+exp(-(weights[df[i,]$y])))})
  tryCatch(nlin.fit <- nls(formula = z ~ a / (1+exp(-(alpha*x + weights[y]))), train, start=list(a=mean(start),alpha=0.001), algorithm = "port"),
           error = return)
  predicted.nlin <- predict(nlin.fit, test)
  
  list(rmse.lin = rmse(predicted.lin - test$z, rep(0, length(predicted.lin))),
       rmse.nlin = rmse(predicted.nlin - test$z, rep(0, length(predicted.nlin))))
}
```

```{r}
res <- replicate(1000, go())
hist(unlist(res[1,]), col = "red")
hist(unlist(res[2,]), add = T, col = "green")
```
